#!/bin/sh

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

echo "+++ lintian output +++"

for changes in $BUILDDIR/*.changes; do
  case $changes in *_source.changes) echo Changes: $changes; continue ;; esac
  su -c "time eatmydata lintian -IE --pedantic --no-tag-display-limit $changes; :" - pbuilder
  echo $changes
done

echo "+++ end of lintian output +++"
