#!/bin/sh

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

set -ex
echo "+++ lintian output +++"

for changes in $BUILDDIR/*.changes; do
  #su -c "lintian -IE --pedantic --no-tag-display-limit $changes; :" - pbuilder
  echo $changes
done

echo "+++ end of lintian output +++"
