#!/bin/sh

DEPSPATH="$DEPSBASE/$DEPS"

if [ -n "$DEPS" ] && [ -d "$DEPSPATH" ] ; then
        apt-get install --assume-yes apt-utils
        ( cd "$DEPSPATH"; apt-ftparchive packages . > Packages )
        echo "deb [trusted=yes] file://$DEPSPATH ./" >> /etc/apt/sources.list
        apt-get update
fi
