#!/bin/sh

SCRIPT_ROOT=$(dirname $(readlink -f $0))
ID=$(id -u)

if [ $ID -ne 0 ]; then
	echo Need root access to setup IPv6 network
	exit 1
fi

sysctl -p $SCRIPT_ROOT/global/etc/sysctl.d/ipv6.conf
$SCRIPT_ROOT/ip-addrlabel_NTT-NGN-fix
service wide-dhcpv6-client restart
