#!/bin/sh

SRC_ROOT=$(readlink -f $(dirname $0))
USR=$(id -un)
[ -z "$USR" ] &&
	USR=$USER
USERID=$(id -ru)
DRYRUN=0
if [ -n "$1" ]; then
	if [ "$1" = "--help" -o "$1" = "-h" ]; then
		echo Usage:
		printf \\\t$0\\\t\\\tupdate\ config\\\n
		printf \\\t$0\ \[--help\|-h\]\\\tshow\ this\ help\\\n
		printf \\\t$0\ \[--dry-run\|-n\]\\\ttest\ but\ no\ real\ change\\\n
		exit
	elif [ "$1" = "--dry-run" -o "$1" = "-n" ]; then
		DRYRUN=1
	fi
fi

logger() {
	echo "$1"'	'"$2"':	'"$3"
}

config_profile() {
	profile=$1
	SU_CMD=
	HOMEDIR=
	IGNOREPATH=
	[ ! -d $SRC_ROOT/$profile ] &&
		return
	if [ "$profile" = "local" ]; then
		HOMEDIR=$(eval echo "~$USR")
		[ "$USERID" -eq 0 ] && 	# su to the user which config/ folder is stored
			SU_CMD="su $USR -c '\"\$0\" \"\$@\"' --"
		# solution mentioned in post: https://stackoverflow.com/questions/12343227
	fi

	cd $SRC_ROOT/$profile
	for item in $(find . -mount -print); do
		# skip if it's a folder
		[ -z "$item" -o ! -e "$item" -o "$item" = "." ] &&
			continue

		append=
		name=$(basename $item)
		path=$(dirname $item)
		if [ "$path" = "." ]; then
			path=""
		else
			path=${path#./}/
		fi									# relative $path, TO here
		src="$SRC_ROOT/$profile/$path$name"	# "source file" in absolute path
		realsrc="$(readlink -f "$src")"
		if [ -n "$IGNOREPATH" ]; then
			case "$src" in
			${IGNOREPATH}*)
				continue
				;;
			*)
				IGNOREPATH=
				;;
			esac
		fi
		case "$path" in
			_*) path=.${path#_}
		esac
		path="$HOMEDIR/$path"				# absolute $path, FROM here

		case "$name" in
		_*+)
			target=.${name#_}
			append=${target%+}
			;;
		*+)
			target=$name
			append=${name%+}
			;;
		_*)
			target=.${name#_}
			;;
		*)
			target="$name"
			;;
		esac
		target="$path$target"				# "$target file" in absolute path

		# file should not exist (symbolic link is OK, we update it if linking to other file)
		if [ -f "$target" -a ! -h "$target" ]; then
			logger '[NG]' "$src" "target exists \"$target\""
			continue
		fi
		# if target folder doesn't exist, simply mkdir it
		if [ ! -d "$path" ]; then
			if [ $DRYRUN -eq 0 ] && ! mkdir -p "$path"; then
				logger '[NG]' "$src" "fail to mkdir \"$path\""
				continue
			else
				logger '[DIR]' "$src" "mkdir \"$path\""
			fi
		fi
		# the special case for "name+" file or folder
		if [ -n "$append" ]; then
			if [ -d "$realsrc" ]; then
				target="${path}${append}/"
				if [ ! -d "$target" ]; then # it's normal if the folder to append already exists
					if [ $DRYRUN -eq 0 ] && ! mkdir -p "$target"; then
						logger '[NG]' "$src" "fail to mkdir \"$target\""
						continue
					else
						logger '[DIR]' "$src" "mkdir \"$target\""
					fi
				fi
				src=${src}/*
				IGNOREPATH="$src"
			else
				if [ -h "$target" ]; then
					logger '[SKIP]' "$src" "\"$path$append\" already appended. please maintain it yourself."
					continue
				else
					logger '[OK]' "$src" "\"$path$append\" appended"
					[ $DRYRUN -eq 0 ] &&
						cat "$src" >> "$path$append"
				fi
			fi
		fi
		if [ "$src" -ef "$target" ] || [ -d "$realsrc" -a -z "$append" ]; then
				# nothing need to do if:
				# 1. $target is already linked to $src, what ever soft or hard link, or
				# 2. $src is folder, but target is not "name+"
				continue
		fi
		if [ $DRYRUN -eq 0 ] && ! eval $SU_CMD ln -sf "$src" "$target"; then
			logger '[NG]' "$src" "fail to make symbolic link to \"$target\""
			continue
		fi
		logger '[OK]' "$src" "symbolic link to \"$target\""
	done
}

[ "$USERID" -eq 0 ] &&
	config_profile global
config_profile local
