#!/bin/sh

SCRIPT_ROOT=$(dirname $(readlink -f $0))

if [ -z "$CONNECT_TIME" ]; then
	sysctl -p /etc/sysctl.d/ipv6.conf 2> /dev/null
	[ -x "${SCRIPT_ROOT}/ip-addrlabel_NTT-NGN-fix" ] &&
		${SCRIPT_ROOT}/ip-addrlabel_NTT-NGN-fix
	if [ "$PPP_IPPARAM" = "ipv6defaultroute" ]; then
		ip -6 r flush default
		ip -6 r add default dev $PPP_IFACE
	fi
	if [ -r /var/run/dhcp6c.pid ]; then
		service wide-dhcpv6-client restart
	else
		service wide-dhcpv6-client start
	fi
else
	[ -r /var/run/dhcp6c.pid ] &&
		service wide-dhcpv6-client stop
	sysctl -p /etc/sysctl.d/no_ipv6.conf
fi

exit 0
